# Sample waypoints configuration
waypoints:
  - name: "start"
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  
  - name: "point1"
    x: 5.0
    y: 0.0
    z: 0.0
    yaw: 1.57  # 90 degrees in radians
  
  - name: "point2"
    x: 5.0
    y: 5.0
    z: 0.0
    yaw: 3.14  # 180 degrees in radians
  
  - name: "point3"
    x: 0.0
    y: 5.0
    z: 0.0
    yaw: 4.71  # 270 degrees in radians
  
  - name: "end"
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0 