waypoints:
  - name: "wp_000"
    x: 0.481594
    y: -0.595697
    z: 0.000000
    yaw: 0.040364
  - name: "wp_001"
    x: 1.512390
    y: -0.554067
    z: 0.000000
    yaw: 0.004521
  - name: "wp_002"
    x: 2.522450
    y: -0.549501
    z: 0.000000
    yaw: -0.028822
  - name: "wp_003"
    x: 3.576649
    y: -0.579893
    z: 0.000000
    yaw: 0.081709
  - name: "wp_004"
    x: 4.630723
    y: -0.493573
    z: 0.000000
    yaw: -0.027885
  - name: "wp_005"
    x: 5.691163
    y: -0.523152
    z: 0.000000
    yaw: -0.014106
  - name: "wp_006"
    x: 6.763824
    y: -0.538283
    z: 0.000000
    yaw: -0.041323
  - name: "wp_007"
    x: 7.781726
    y: -0.580370
    z: 0.000000
    yaw: -0.149408
  - name: "wp_008"
    x: 8.796103
    y: -0.733064
    z: 0.000000
    yaw: -1.285519
  - name: "wp_009"
    x: 9.191094
    y: -2.079888
    z: 0.000000
    yaw: -1.489968
  - name: "wp_010"
    x: 9.303308
    y: -3.465164
    z: 0.000000
    yaw: -1.213581
  - name: "wp_011"
    x: 9.662938
    y: -4.428733
    z: 0.000000
    yaw: -1.316903
  - name: "wp_012"
    x: 9.939139
    y: -5.493121
    z: 0.000000
    yaw: -1.287458
  - name: "wp_013"
    x: 10.233017
    y: -6.502411
    z: 0.000000
    yaw: -1.264626
  - name: "wp_014"
    x: 10.542134
    y: -7.480291
    z: 0.000000
    yaw: -0.833256
  - name: "wp_015"
    x: 11.224148
    y: -8.230920
    z: 0.000000
    yaw: -0.019606
  - name: "wp_016"
    x: 12.581443
    y: -8.257535
    z: 0.000000
    yaw: -0.155242
  - name: "wp_017"
    x: 13.599754
    y: -8.416902
    z: 0.000000
    yaw: 0.099274
  - name: "wp_018"
    x: 14.803908
    y: -8.296966
    z: 0.000000
    yaw: -0.059275
  - name: "wp_019"
    x: 15.847310
    y: -8.358886
    z: 0.000000
    yaw: -0.052728
  - name: "wp_020"
    x: 17.859144
    y: -8.465064
    z: 0.000000
    yaw: -0.039552
  - name: "wp_021"
    x: 18.956997
    y: -8.508509
    z: 0.000000
    yaw: -0.046106
  - name: "wp_022"
    x: 20.007460
    y: -8.556975
    z: 0.000000
    yaw: -0.053884
  - name: "wp_023"
    x: 21.037146
    y: -8.612513
    z: 0.000000
    yaw: -0.171729
  - name: "wp_024"
    x: 22.050457
    y: -8.788259
    z: 0.000000
    yaw: -0.044988
  - name: "wp_025"
    x: 23.065693
    y: -8.833962
    z: 0.000000
    yaw: -0.039390
  - name: "wp_026"
    x: 24.127584
    y: -8.875812
    z: 0.000000
    yaw: -0.056540
  - name: "wp_027"
    x: 25.144117
    y: -8.933348
    z: 0.000000
    yaw: 0.000199
  - name: "wp_028"
    x: 26.208210
    y: -8.933136
    z: 0.000000
    yaw: -0.051012
  - name: "wp_029"
    x: 27.286118
    y: -8.988170
    z: 0.000000
    yaw: -0.176985
  - name: "wp_030"
    x: 28.302641
    y: -9.169981
    z: 0.000000
    yaw: -0.087166
  - name: "wp_031"
    x: 29.393177
    y: -9.265280
    z: 0.000000
    yaw: -0.101402
  - name: "wp_032"
    x: 30.424994
    y: -9.370268
    z: 0.000000
    yaw: -0.043900
  - name: "wp_033"
    x: 31.522434
    y: -9.418476
    z: 0.000000
    yaw: -0.078370
  - name: "wp_034"
    x: 32.568710
    y: -9.500641
    z: 0.000000
    yaw: -0.073493
  - name: "wp_035"
    x: 33.650578
    y: -9.580294
    z: 0.000000
    yaw: 0.249391
  - name: "wp_036"
    x: 34.678707
    y: -9.318436
    z: 0.000000
    yaw: 1.638038
  - name: "wp_037"
    x: 34.568565
    y: -7.682899
    z: 0.000000
    yaw: 2.039332
  - name: "wp_038"
    x: 33.907333
    y: -6.376438
    z: 0.000000
    yaw: 1.640967
  - name: "wp_039"
    x: 33.831650
    y: -5.299652
    z: 0.000000
    yaw: 1.457155
  - name: "wp_040"
    x: 33.957245
    y: -4.199224
    z: 0.000000
    yaw: 1.864669
  - name: "wp_041"
    x: 33.540565
    y: -2.822386
    z: 0.000000
    yaw: 2.551754
  - name: "wp_042"
    x: 32.532101
    y: -2.147398
    z: 0.000000
    yaw: 2.960425
  - name: "wp_043"
    x: 31.071199
    y: -1.879796
    z: 0.000000
    yaw: 2.978950
  - name: "wp_044"
    x: 30.057932
    y: -1.713527
    z: 0.000000
    yaw: 3.058052
  - name: "wp_045"
    x: 29.041445
    y: -1.628411
    z: 0.000000
    yaw: 3.030582
  - name: "wp_046"
    x: 27.947668
    y: -1.506489
    z: 0.000000
    yaw: 3.089566
  - name: "wp_047"
    x: 26.870169
    y: -1.450380
    z: 0.000000
    yaw: 3.132521
  - name: "wp_048"
    x: 25.755625
    y: -1.440269
    z: 0.000000
    yaw: 3.070646
  - name: "wp_049"
    x: 24.682894
    y: -1.364034
    z: 0.000000
    yaw: 3.105461
  - name: "wp_050"
    x: 23.608816
    y: -1.325208
    z: 0.000000
    yaw: 3.106149
  - name: "wp_051"
    x: 22.458536
    y: -1.284421
    z: 0.000000
    yaw: 3.114528
  - name: "wp_052"
    x: 21.400467
    y: -1.255778
    z: 0.000000
    yaw: 3.021613
  - name: "wp_053"
    x: 20.321417
    y: -1.125689
    z: 0.000000
    yaw: -3.134222
  - name: "wp_054"
    x: 18.292780
    y: -1.140642
    z: 0.000000
    yaw: 3.109295
  - name: "wp_055"
    x: 17.172861
    y: -1.104459
    z: 0.000000
    yaw: 3.119311
  - name: "wp_056"
    x: 16.131901
    y: -1.081261
    z: 0.000000
    yaw: 3.074853
  - name: "wp_057"
    x: 14.999331
    y: -1.005561
    z: 0.000000
    yaw: 3.074663
  - name: "wp_058"
    x: 13.972724
    y: -0.936748
    z: 0.000000
    yaw: 3.080446
  - name: "wp_059"
    x: 12.848914
    y: -0.867945
    z: 0.000000
    yaw: 3.073594
  - name: "wp_060"
    x: 11.706167
    y: -0.790119
    z: 0.000000
    yaw: -3.097429
  - name: "wp_061"
    x: 10.601838
    y: -0.838922
    z: 0.000000
    yaw: -2.439618
  - name: "wp_062"
    x: 9.571431
    y: -1.710306
    z: 0.000000
    yaw: -1.550335
  - name: "wp_063"
    x: 9.607241
    y: -3.460155
    z: 0.000000
    yaw: -1.226506
  - name: "wp_064"
    x: 9.983114
    y: -4.508408
    z: 0.000000
    yaw: -1.467050
  - name: "wp_065"
    x: 10.089376
    y: -5.528981
    z: 0.000000
    yaw: -1.329750
  - name: "wp_066"
    x: 10.346246
    y: -6.573905
    z: 0.000000
    yaw: -1.507648
  - name: "wp_067"
    x: 10.411997
    y: -7.613739
    z: 0.000000
    yaw: -2.247430
  - name: "wp_068"
    x: 9.760258
    y: -8.425260
    z: 0.000000
    yaw: 3.107453
  - name: "wp_069"
    x: 7.910257
    y: -8.362077
    z: 0.000000
    yaw: -3.106226
  - name: "wp_070"
    x: 6.859714
    y: -8.399246
    z: 0.000000
    yaw: 3.083229
  - name: "wp_071"
    x: 5.857270
    y: -8.340673
    z: 0.000000
    yaw: 2.956081
  - name: "wp_072"
    x: 4.868900
    y: -8.155187
    z: 0.000000
    yaw: 2.962884
  - name: "wp_073"
    x: 3.831541
    y: -7.967803
    z: 0.000000
    yaw: 3.010248
  - name: "wp_074"
    x: 2.716461
    y: -7.820495
    z: 0.000000
    yaw: 2.949928
  - name: "wp_075"
    x: 1.732499
    y: -7.629560
    z: 0.000000
    yaw: 2.458888
  - name: "wp_076"
    x: 0.688702
    y: -6.780802
    z: 0.000000
    yaw: 1.722277
  - name: "wp_077"
    x: 0.370003
    y: -4.693030
    z: 0.000000
    yaw: 1.875326
  - name: "wp_078"
    x: -0.192902
    y: -2.902088
    z: 0.000000
    yaw: 1.914302
  - name: "wp_079"
    x: -0.550830
    y: -1.901411
    z: 0.000000
    yaw: 1.807754
  - name: "wp_080"
    x: -0.800107
    y: -0.869186
    z: 0.000000
    yaw: 0.005078
  - name: "wp_081"
    x: -0.079486
    y: -0.865527
    z: 0.000000
    yaw: 0.005078
