input_topic: "/points_raw"
output_topic: "/pc_roi"
output_frame: "base_link_est"
use_tf: true

roi_x_min: 0.0
roi_x_max: 20.0
roi_y_min: -6.0
roi_y_max: 6.0
z_min: -1.0
z_max: 3.0
voxel: 0.05

log_interval: 2.0
