---
# Costmap for static orchard maps (no sensor obstacle layer).
footprint: [[0.575, 0.23], [0.575, -0.23], [-0.575, -0.23], [-0.575, 0.23]]

transform_tolerance: 0.2
always_send_full_costmap: true

obstacle_layer:
  enabled: false

inflation_layer:
  enabled: true
  cost_scaling_factor: 15.0
  inflation_radius: 0.25

static_layer:
  enabled: true
  map_topic: "/map"

