obstacle_layer:
  observation_sources: laser_scan_sensor tree_cloud
  tree_cloud:
    data_type: PointCloud2
    topic: /orchard_segmentation/tree_cloud
    marking: true
    clearing: false
    min_obstacle_height: 0.6
    max_obstacle_height: 1.6
    obstacle_range: 4.0
    raytrace_range: 5.0

